# The URL the site will be built for
base_url = "https://hackers267.github.io/rust-note"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
theme = "blow"
title = "Rust笔记"
default_language = "zh"


taxonomies = [
 { name = "tags" , res = true }
]

[slugify]
anchors = "safe"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
enable_multilingue = false
enable_search = false
enable_sidebar = false
enable_navbar = true
enable_adsense = false

[extra.navbar]
title = "Rust"
items = [
  { lang = "zh", links = [
   { url = "/", name = "首页" },
   { url = "/std", name = "标准库" } ,
   { url = "/third", name = "第三方库" },
   { url = "/post", name = "文章" },
   { url = "/tags", name = "标签" },
  ] },
]

[extra.index]
title = "Rust"
image = "https://avatars.githubusercontent.com/u/22020318?v=4"
image_alt = "silence_zhpf"

[extra.default_author]
name = "silence_zhpf"
avatar = "https://avatars.githubusercontent.com/u/22020318?v=4"
avatar_alt = "silence_zhpf"

[extra.social]
github = "https://github.com/hackers267/rust-note"
gitlab = false
twitter = false
linkedin = false
stackoverflow = false
telegram = false
email = "silence_zhpf"
